# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Edit_book_window(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 626)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setMinimumSize(QtCore.QSize(0, 0))
        self.textBrowser.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textBrowser.setStyleSheet("background: transparent;\n"
"border: none;")
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_3.addWidget(self.textBrowser)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_titulo_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo_2.setMinimumSize(QtCore.QSize(300, 50))
        self.label_titulo_2.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_titulo_2.setFont(font)
        self.label_titulo_2.setObjectName("label_titulo_2")
        self.horizontalLayout_9.addWidget(self.label_titulo_2)
        self.line_titulo_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.line_titulo_2.setMinimumSize(QtCore.QSize(300, 50))
        self.line_titulo_2.setMaximumSize(QtCore.QSize(300, 50))
        self.line_titulo_2.setStyleSheet("background: transparent;\n"
" border: 2px solid black;")
        self.line_titulo_2.setObjectName("line_titulo_2")
        self.horizontalLayout_9.addWidget(self.line_titulo_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_autor_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_autor_2.setMinimumSize(QtCore.QSize(300, 50))
        self.label_autor_2.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_autor_2.setFont(font)
        self.label_autor_2.setObjectName("label_autor_2")
        self.horizontalLayout_10.addWidget(self.label_autor_2)
        self.line_autor_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.line_autor_2.setMinimumSize(QtCore.QSize(300, 50))
        self.line_autor_2.setMaximumSize(QtCore.QSize(300, 50))
        self.line_autor_2.setStyleSheet("background: transparent;\n"
" border: 2px solid black;")
        self.line_autor_2.setObjectName("line_autor_2")
        self.horizontalLayout_10.addWidget(self.line_autor_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_Qpaginas_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_Qpaginas_2.setMinimumSize(QtCore.QSize(300, 50))
        self.label_Qpaginas_2.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_Qpaginas_2.setFont(font)
        self.label_Qpaginas_2.setObjectName("label_Qpaginas_2")
        self.horizontalLayout_11.addWidget(self.label_Qpaginas_2)
        self.line_Qpaginas_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.line_Qpaginas_2.setMinimumSize(QtCore.QSize(300, 50))
        self.line_Qpaginas_2.setMaximumSize(QtCore.QSize(300, 50))
        self.line_Qpaginas_2.setStyleSheet("background: transparent;\n"
" border: 2px solid black;")
        self.line_Qpaginas_2.setObjectName("line_Qpaginas_2")
        self.horizontalLayout_11.addWidget(self.line_Qpaginas_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_publicacao_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_publicacao_2.setMinimumSize(QtCore.QSize(300, 50))
        self.label_publicacao_2.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_publicacao_2.setFont(font)
        self.label_publicacao_2.setObjectName("label_publicacao_2")
        self.horizontalLayout_12.addWidget(self.label_publicacao_2)
        self.line_publicacao_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.line_publicacao_2.setMinimumSize(QtCore.QSize(300, 50))
        self.line_publicacao_2.setMaximumSize(QtCore.QSize(300, 50))
        self.line_publicacao_2.setStyleSheet("background: transparent;\n"
" border: 2px solid black;")
        self.line_publicacao_2.setObjectName("line_publicacao_2")
        self.horizontalLayout_12.addWidget(self.line_publicacao_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.voltar = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.voltar.sizePolicy().hasHeightForWidth())
        self.voltar.setSizePolicy(sizePolicy)
        self.voltar.setMinimumSize(QtCore.QSize(100, 50))
        self.voltar.setMaximumSize(QtCore.QSize(100, 50))
        self.voltar.setObjectName("voltar")
        self.horizontalLayout_13.addWidget(self.voltar)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.Editar = QtWidgets.QPushButton(self.centralwidget)
        self.Editar.setMinimumSize(QtCore.QSize(100, 50))
        self.Editar.setMaximumSize(QtCore.QSize(100, 50))
        self.Editar.setObjectName("Editar")
        self.horizontalLayout_13.addWidget(self.Editar)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; color:#55007f;\">Editar livro</span></p></body></html>"))
        self.label_titulo_2.setText(_translate("MainWindow", "Título do livro:"))
        self.label_autor_2.setText(_translate("MainWindow", "Autor Principal:"))
        self.label_Qpaginas_2.setText(_translate("MainWindow", "Quantidade de páginas:"))
        self.label_publicacao_2.setText(_translate("MainWindow", "Ano de publicação:"))
        self.voltar.setText(_translate("MainWindow", "Voltar"))
        self.Editar.setText(_translate("MainWindow", "Editar Livro"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
