# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sign_up_books.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Sign_up_books_window(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setMinimumSize(QtCore.QSize(0, 0))
        self.textBrowser.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textBrowser.setStyleSheet("background: transparent;\n"
"border: none;")
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo.setMinimumSize(QtCore.QSize(300, 50))
        self.label_titulo.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_titulo.setFont(font)
        self.label_titulo.setObjectName("label_titulo")
        self.horizontalLayout_7.addWidget(self.label_titulo)
        self.line_titulo = QtWidgets.QLineEdit(self.centralwidget)
        self.line_titulo.setMinimumSize(QtCore.QSize(300, 50))
        self.line_titulo.setMaximumSize(QtCore.QSize(300, 50))
        self.line_titulo.setStyleSheet("background: transparent;\n"
" border: 2px solid black;")
        self.line_titulo.setObjectName("line_titulo")
        self.horizontalLayout_7.addWidget(self.line_titulo)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_autor = QtWidgets.QLabel(self.centralwidget)
        self.label_autor.setMinimumSize(QtCore.QSize(300, 50))
        self.label_autor.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_autor.setFont(font)
        self.label_autor.setObjectName("label_autor")
        self.horizontalLayout_8.addWidget(self.label_autor)
        self.line_autor = QtWidgets.QLineEdit(self.centralwidget)
        self.line_autor.setMinimumSize(QtCore.QSize(300, 50))
        self.line_autor.setMaximumSize(QtCore.QSize(300, 50))
        self.line_autor.setStyleSheet("background: transparent;\n"
" border: 2px solid black;")
        self.line_autor.setObjectName("line_autor")
        self.horizontalLayout_8.addWidget(self.line_autor)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_Qpaginas = QtWidgets.QLabel(self.centralwidget)
        self.label_Qpaginas.setMinimumSize(QtCore.QSize(300, 50))
        self.label_Qpaginas.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_Qpaginas.setFont(font)
        self.label_Qpaginas.setObjectName("label_Qpaginas")
        self.horizontalLayout_5.addWidget(self.label_Qpaginas)
        self.line_Qpaginas = QtWidgets.QLineEdit(self.centralwidget)
        self.line_Qpaginas.setMinimumSize(QtCore.QSize(300, 50))
        self.line_Qpaginas.setMaximumSize(QtCore.QSize(300, 50))
        self.line_Qpaginas.setStyleSheet("background: transparent;\n"
" border: 2px solid black;")
        self.line_Qpaginas.setObjectName("line_Qpaginas")
        self.horizontalLayout_5.addWidget(self.line_Qpaginas)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_publicacao = QtWidgets.QLabel(self.centralwidget)
        self.label_publicacao.setMinimumSize(QtCore.QSize(300, 50))
        self.label_publicacao.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_publicacao.setFont(font)
        self.label_publicacao.setObjectName("label_publicacao")
        self.horizontalLayout_6.addWidget(self.label_publicacao)
        self.line_publicacao = QtWidgets.QLineEdit(self.centralwidget)
        self.line_publicacao.setMinimumSize(QtCore.QSize(300, 50))
        self.line_publicacao.setMaximumSize(QtCore.QSize(300, 50))
        self.line_publicacao.setStyleSheet("background: transparent;\n"
" border: 2px solid black;")
        self.line_publicacao.setObjectName("line_publicacao")
        self.horizontalLayout_6.addWidget(self.line_publicacao)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.voltar_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.voltar_2.sizePolicy().hasHeightForWidth())
        self.voltar_2.setSizePolicy(sizePolicy)
        self.voltar_2.setMinimumSize(QtCore.QSize(100, 50))
        self.voltar_2.setMaximumSize(QtCore.QSize(100, 50))
        self.voltar_2.setObjectName("voltar_2")
        self.horizontalLayout_4.addWidget(self.voltar_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.cadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.cadastrar.setMinimumSize(QtCore.QSize(100, 50))
        self.cadastrar.setMaximumSize(QtCore.QSize(100, 50))
        self.cadastrar.setObjectName("cadastrar")
        self.horizontalLayout_4.addWidget(self.cadastrar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; color:#55007f;\">Cadastrar livros</span></p></body></html>"))
        self.label_titulo.setText(_translate("MainWindow", "Título do livro:"))
        self.label_autor.setText(_translate("MainWindow", "Autor Principal:"))
        self.label_Qpaginas.setText(_translate("MainWindow", "Quantidade de páginas:"))
        self.label_publicacao.setText(_translate("MainWindow", "Ano de publicação:"))
        self.voltar_2.setText(_translate("MainWindow", "Voltar"))
        self.cadastrar.setText(_translate("MainWindow", "Cadastrar Livro"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
